//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_status
    {
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public decimal grandtotal { get; set; }
        public string ordstatus { get; set; }
        public string paymtd { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
