//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casestudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_food
    {
        public int orderF_id { get; set; }
        public int customer_id { get; set; }
        public int restaurant_id { get; set; }
        public int food_id { get; set; }
        public string paymentmethod { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual fooditem fooditem { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
